platform :ios, '7.0'
pod 'Facade', '~> 1.1.0'
pod 'UIColor-MoreColors', '~> 1.1.0'
pod 'UILabel+ContentSize', '~> 1.0.3'
pod 'AFNetworking', '~> 2.0'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'AGLocationDispatcher', '~> 0.0.7.2'
#pod 'TTTAttributedLabel', '~> 1.13.4'
#pod 'RichStyleLabel', '~> 0.0.1'
#pod 'ZCAnimatedLabel', '~> 0.0.3'
pod 'YTKKeyValueStore', '~> 0.1.2'
pod 'AESCrypt', '~> 0.0.1'
#pod 'MD5Digest', '~> 1.0.1'
pod 'NSString+TBEncryption', '~> 1.0'
pod 'EPSWebViewController', '~> 0.1'
#pod 'DWUWebView'
use_frameworks!
pod 'ChameleonFramework'
pod 'WTAZoomNavigationController', '~> 1.0.7'
#pod 'UINavigationItem-iOS7Spacing', '~> 0.2'
pod 'SVPullToRefreshImprove', '~> 0.5'
pod 'UIViewController+ODStatusBar', '~> 0.1.5'
pod 'NJKScrollFullScreen', '~> 0.2.6'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MD5Digest', '~> 1.1.0'